import type { Viewport, Metadata } from "next";

export const metadata: Metadata = {
  title: "Works",
  description: "Explore my projects.",
  publisher: "Suin Kim",
  openGraph: {
    title: "Works",
    description: "Explore my projects.",
    url: "https://sulnklm.com/works",
    siteName: "Suin Kim Portfolio",
    // images: [
    //   {
    //     url: "https://sulnklm.com/og-image.png",
    //     width: 1200,
    //     height: 630,
    //     alt: "Suin Kim Portfolio",
    //   },
    // ],
    locale: "en_US",
    type: "website",
  },
  keywords: [
    "Suin Kim",
    "Portfolio",
    "Works",
    "Projects",
    "Web Development",
    "UI/UX Design",
    "Graphic Design",
    "Software Development",
    "Front-end Development",
    "Full-stack Design",
    "React",
    "Next.js",
    "JavaScript",
    "TypeScript",
    "HTML",
    "CSS",
    "Figma",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Design",
    "Development",
    "Programming",
    "Coding",
    "Tech",
    "Technology",
    "Software Engineering",
    "Web Design",
    "User Experience",
    "User Interface",
    "Responsive Design",
    "Accessibility",
    "Performance Optimization",
    "SEO",
    "Web Applications",
    "Mobile Applications",
    "Cross-platform Development",
    "Agile Development",
    "Version Control",
    "Git",
    "Open Source",
    "Portfolio Website",
    "Personal Projects",
    "Professional Projects",
    "Case Studies",
    "Project Showcase",
    "Project Management",
    "Collaboration",
    "Teamwork",
    "Problem Solving",
    "Creativity",
    "Innovation",
    "Design Thinking",
    "User Research",
    "Wireframing",
    "Prototyping",
    "Visual Design",
    "Interaction Design",
    "Branding",
    "Digital Marketing",
    "Content Creation",
    "Social Media",
    "Online Presence",
    "Freelance",
    "Entrepreneurship",
    "Career Development",
    "Professional Growth",
    "Networking",
    "Tech Community",
    "Tech Industry",
    "Tech Trends",
    "Tech News",
    "Tech Blogs",
    "Tech Podcasts",
    "Tech Conferences",
    "Design Community",
    "Design Trends",
  ],
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
  themeColor: "#ffffff",
};

export async function generateMetadata(): Promise<Metadata> {
  return metadata;
}